import './analytics.js'
import './foreach-polyfill.js'
import './header.js';
import './menu.js';
import './preloader.js';
import './steps.js';
import './accordion.js';
import './cookie.js';
import './reviews.js';
import './popup.js';
import './lazyload.js';